<?php
declare(strict_types=1);

$this->headTitle($this->title);

?>
<table class="table-responsive table-striped table-hover table-group-divider">
  <thead>
  <tr   class="bg-primary">
      <th scope="col">#</th>
      <th scope="col">User Name</th>
      <th scope="col">Email</th>
      <th scope="col">Password</th>
      <th scope="col">Actualizar</th>
      <th scope="col">Eliminar</th>
  </thead>
<tbody>
    <?php
        if(isset($this->users)) :
            foreach($this->users as $user) :
    ?>
            <tr class="table-active">
            <td><?=$user->getId()?></td>
            <td><?=$user->getUserName()?></td>
            <td><?=$user->getEmail()?></td>
            <td><?=$user->getPassword()?></td>
            <td><a href="/user/edit/<?=$user->getId()?>" class="btn btn-success">Editar</a></td>
            <td><a href="/user/delete/<?=$user->getId()?>" class="btn btn-danger">Eliminar</a></td>
            </tr>
    <?php
            endforeach;
        endif;
    ?>
</tbody>
</table>

